INSERT INTO teams ( name, short_name, country, active) VALUES
( 'Chennai Super Kings',         'CSK',  'India', true),
(  'Mumbai Indians',              'MI',   'India', true),
(  'Royal Challengers Bengaluru', 'RCB',  'India', true),
( 'Kolkata Knight Riders',       'KKR',  'India', true),
('Sunrisers Hyderabad',         'SRH',  'India', true),
(  'Rajasthan Royals',            'RR',   'India', true),
('Delhi Capitals',              'DC',   'India', true),
( 'Punjab Kings',                'PBKS', 'India', true),
('Gujarat Titans',              'GT',   'India', true),
('Lucknow Super Giants',        'LSG',  'India', true);
INSERT INTO venues (name, city, state, country, pitch_type, straight_boundary_meters, square_boundary_meters, capacity) VALUES
('MA Chidambaram Stadium',         'Chennai',   'Tamil Nadu',       'India', 'Spin',    65, 60, 38000),
('Wankhede Stadium',               'Mumbai',    'Maharashtra',      'India', 'Batting', 72, 62, 33000),
('M Chinnaswamy Stadium',          'Bengaluru', 'Karnataka',        'India', 'Batting', 73, 65, 35000),
('Eden Gardens',                   'Kolkata',   'West Bengal',      'India', 'Batting', 80, 52, 68000),
('Rajiv Gandhi Intl Cricket Stad', 'Hyderabad', 'Telangana',        'India', 'Batting', 72, 62, 55000),
('Sawai Mansingh Stadium',         'Jaipur',    'Rajasthan',        'India', 'Batting', 72, 60, 30000),
('Arun Jaitley Stadium',           'Delhi',     'Delhi',            'India', 'Batting', 72, 60, 35000),
('Punjab Cricket Association Stad','Mohali',    'Punjab',           'India', 'Batting', 73, 65, 26000),
('Narendra Modi Stadium',          'Ahmedabad', 'Gujarat',          'India', 'Batting', 82, 65, 132000),
('Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium', 'Lucknow', 'Uttar Pradesh', 'India', 'Batting', 72, 62, 50000);
INSERT INTO players (full_name, short_name, role, batting_style, bowling_style, team_id, captain, wicket_keeper, active) VALUES
('Ruturaj Gaikwad',   'CSK-Ruturaj',   'BATTER',       'RIGHT_HAND_BAT', NULL,                   1, true,  false, true),
('MS Dhoni',          'Dhoni',     'WICKET_KEEPER', 'RIGHT_HAND_BAT', NULL,                   1, false, true,  true),
('Sanju Samson',      'Samson',    'WICKET_KEEPER', 'RIGHT_HAND_BAT', NULL,                   1, false, true,  true),
('Dewald Brevis',     'Brevis',    'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_MEDIUM',     1, false, false, true),
('Ayush Mhatre',      'Mhatre',    'BATTER',        'RIGHT_HAND_BAT', NULL,                   1, false, false, true),
('Kartik Sharma',     'K Sharma',  'BATTER',        'RIGHT_HAND_BAT', NULL,                   1, false, false, true),
('Sarfaraz Khan',     'Sarfaraz',  'BATTER',        'RIGHT_HAND_BAT', NULL,                   1, false, false, true),
('Urvil Patel',       'U Patel',   'WICKET_KEEPER', 'RIGHT_HAND_BAT', NULL,                   1, false, true,  true),
('Jamie Overton',     'Overton',   'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       1, false, false, true),
('Ramakrishna Ghosh', 'R Ghosh',   'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_MEDIUM',     1, false, false, true),
('Prashant Veer',     'P Veer',    'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_MEDIUM',     1, false, false, true),
('Matthew Short',     'CSK-Short',   'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_OFFBREAK',   1, false, false, true),
('Aman Khan',         'A Khan',    'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_MEDIUM',     1, false, false, true),
('Zak Foulkes',       'Foulkes',   'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       1, false, false, true),
('Shivam Dube',       'S Dube',    'ALL_ROUNDER',   'LEFT_HAND_BAT',  'RIGHT_ARM_MEDIUM',     1, false, false, true),
('Khaleel Ahmed',     'Khaleel',   'BOWLER',        'LEFT_HAND_BAT',  'LEFT_ARM_FAST',        1, false, false, true),
('Noor Ahmad',        'Noor',      'BOWLER',        'LEFT_HAND_BAT',  'LEFT_ARM_SPIN',        1, false, false, true),
('Anshul Kamboj',     'Kamboj',    'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       1, false, false, true),
('Mukesh Choudhary',  'M Choudhary','BOWLER',       'LEFT_HAND_BAT',  'LEFT_ARM_FAST',        1, false, false, true),
('Shreyas Gopal',     'S Gopal',   'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_LEGBREAK',   1, false, false, true),
('Gurjapneet Singh',  'Gurjapneet','BOWLER',        'RIGHT_HAND_BAT', 'LEFT_ARM_FAST',        1, false, false, true),
('Akeal Hosein',      'Hosein',    'BOWLER',        'LEFT_HAND_BAT',  'LEFT_ARM_SPIN',        1, false, false, true),
('Matt Henry',        'M Henry',   'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       1, false, false, true),
('Rahul Chahar',      'R Chahar',  'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_LEGBREAK',   1, false, false, true),
('Spencer Johnson',   'CSK-Johnson', 'BOWLER',        'LEFT_HAND_BAT',  'LEFT_ARM_FAST',        1, false, false, true);
INSERT INTO players (full_name, short_name, role, batting_style, bowling_style, team_id, captain, wicket_keeper, active) VALUES
('Rohit Sharma',        'MI-Rohit',      'BATTER',        'RIGHT_HAND_BAT', NULL,                   2, false, false, true),
('Suryakumar Yadav',    'SKY',        'BATTER',        'RIGHT_HAND_BAT', NULL,                   2, false, false, true),
('Ryan Rickelton',      'Rickelton',  'WICKET_KEEPER', 'LEFT_HAND_BAT',  NULL,                   2, false, true,  true),
('Quinton de Kock',     'De Kock',    'WICKET_KEEPER', 'LEFT_HAND_BAT',  NULL,                   2, false, true,  true),
('Robin Minz',          'R Minz',     'BATTER',        'RIGHT_HAND_BAT', NULL,                   2, false, false, true),
('N. Tilak Varma',      'MI-Tilak',      'BATTER',        'LEFT_HAND_BAT',  NULL,                   2, false, false, true),
('Hardik Pandya',       'MI-Hardik',     'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       2, true,  false, true),
('Naman Dhir',          'N Dhir',     'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_OFFBREAK',   2, false, false, true),
('Mitchell Santner',    'Santner',    'ALL_ROUNDER',   'LEFT_HAND_BAT',  'LEFT_ARM_SPIN',        2, false, false, true),
('Raj Angad Bawa',      'R Bawa',     'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       2, false, false, true),
('Corbin Bosch',        'C Bosch',    'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       2, false, false, true),
('Will Jacks',          'Jacks',      'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_OFFBREAK',   2, false, false, true),
('Shardul Thakur',      'Shardul',    'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       2, false, false, true),
('Sherfane Rutherford', 'Rutherford', 'ALL_ROUNDER',   'LEFT_HAND_BAT',  'RIGHT_ARM_MEDIUM',     2, false, false, true),
('Mayank Rawat',        'M Rawat',    'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_MEDIUM',     2, false, false, true),
('Danish Malewar',      'Malewar',    'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_MEDIUM',     2, false, false, true),
('Jasprit Bumrah',      'MI-Bumrah',     'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       2, false, false, true),
('Trent Boult',         'T Boult',    'BOWLER',        'LEFT_HAND_BAT',  'LEFT_ARM_FAST',        2, false, false, true),
('Deepak Chahar',       'D Chahar',   'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       2, false, false, true),
('Mayank Markande',     'Markande',   'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_LEGBREAK',   2, false, false, true),
('Allah Ghazanfar',     'Ghazanfar',  'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_OFFBREAK',   2, false, false, true),
('Raghu Sharma',        'R Sharma',   'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_LEGBREAK',   2, false, false, true),
('Ashwani Kumar',       'A Kumar',    'BOWLER',        'RIGHT_HAND_BAT', 'LEFT_ARM_FAST',        2, false, false, true),
('Mohammed Izhar',      'M Izhar',    'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       2, false, false, true),
('Keshav Maharaj',      'Maharaj',    'BOWLER',        'LEFT_HAND_BAT',  'LEFT_ARM_SPIN',        2, false, false, true);
INSERT INTO players (full_name, short_name, role, batting_style, bowling_style, team_id, captain, wicket_keeper, active) VALUES
('Rajat Patidar',     'Patidar',   'BATTER',        'RIGHT_HAND_BAT', NULL,                   3, true,  false, true),
('Virat Kohli',       'RCB-Kohli',     'BATTER',        'RIGHT_HAND_BAT', NULL,                   3, false, false, true),
('Devdutt Padikkal',  'Padikkal',  'BATTER',        'LEFT_HAND_BAT',  NULL,                   3, false, false, true),
('Phil Salt',         'Salt',      'WICKET_KEEPER', 'RIGHT_HAND_BAT', NULL,                   3, false, true,  true),
('Jitesh Sharma',     'J Sharma',  'WICKET_KEEPER', 'RIGHT_HAND_BAT', NULL,                   3, false, true,  true),
('Jordan Cox',        'J Cox',     'WICKET_KEEPER', 'RIGHT_HAND_BAT', NULL,                   3, false, true,  true),
('Krunal Pandya',     'Krunal',    'ALL_ROUNDER',   'LEFT_HAND_BAT',  'LEFT_ARM_SPIN',        3, false, false, true),
('Venkatesh Iyer',    'V Iyer',    'ALL_ROUNDER',   'LEFT_HAND_BAT',  'RIGHT_ARM_MEDIUM',     3, false, false, true),
('Tim David',         'T David',   'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_OFFBREAK',   3, false, false, true),
('Romario Shepherd',  'Shepherd',  'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       3, false, false, true),
('Jacob Bethell',     'Bethell',   'ALL_ROUNDER',   'LEFT_HAND_BAT',  'LEFT_ARM_SPIN',        3, false, false, true),
('Swapnil Singh',     'Swapnil',   'ALL_ROUNDER',   'LEFT_HAND_BAT',  'LEFT_ARM_SPIN',        3, false, false, true),
('Mangesh Yadav',     'RCB-M Yadav',   'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       3, false, false, true),
('Vicky Ostwal',      'Ostwal',    'ALL_ROUNDER',   'LEFT_HAND_BAT',  'LEFT_ARM_SPIN',        3, false, false, true),
('Satvik Deswal',     'Deswal',    'ALL_ROUNDER',   'LEFT_HAND_BAT',  'LEFT_ARM_SPIN',        3, false, false, true),
('Vihaan Malhotra',   'Malhotra',  'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_MEDIUM',     3, false, false, true),
('Kanishk Chouhan',   'Chouhan',   'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_MEDIUM',     3, false, false, true),
('Josh Hazlewood',    'RCB-Hazlewood', 'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       3, false, false, true),
('Bhuvneshwar Kumar', 'Bhuvi',     'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_MEDIUM',     3, false, false, true),
('Rasikh Dar',        'Rasikh',    'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       3, false, false, true),
('Suyash Sharma',     'Suyash',    'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_LEGBREAK',   3, false, false, true),
('Nuwan Thushara',    'Thushara',  'BOWLER',        'LEFT_HAND_BAT',  'RIGHT_ARM_FAST',       3, false, false, true),
('Yash Dayal',        'Y Dayal',   'BOWLER',        'LEFT_HAND_BAT',  'LEFT_ARM_FAST',        3, false, false, true),
('Jacob Duffy',       'J Duffy',   'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       3, false, false, true),
('Abinandan Singh',   'Abinandan', 'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_MEDIUM',     3, false, false, true);
INSERT INTO players (full_name, short_name, role, batting_style, bowling_style, team_id, captain, wicket_keeper, active) VALUES
('Ajinkya Rahane',       'Rahane',    'BATTER',        'RIGHT_HAND_BAT', NULL,                   4, true,  false, true),
('Rinku Singh',          'KKR-Rinku',     'BATTER',        'LEFT_HAND_BAT',  NULL,                   4, false, false, true),
('Angkrish Raghuvanshi', 'Angkrish',  'BATTER',        'RIGHT_HAND_BAT', NULL,                   4, false, false, true),
('Manish Pandey',        'M Pandey',  'BATTER',        'RIGHT_HAND_BAT', NULL,                   4, false, false, true),
('Finn Allen',           'F Allen',   'WICKET_KEEPER', 'RIGHT_HAND_BAT', NULL,                   4, false, true,  true),
('Tim Seifert',          'Seifert',   'WICKET_KEEPER', 'RIGHT_HAND_BAT', NULL,                   4, false, true,  true),
('Rovman Powell',        'Powell',    'BATTER',        'RIGHT_HAND_BAT', NULL,                   4, false, false, true),
('Tejasvi Singh',        'Tejasvi',   'BATTER',        'RIGHT_HAND_BAT', NULL,                   4, false, false, true),
('Rahul Tripathi',       'R Tripathi','BATTER',        'RIGHT_HAND_BAT', NULL,                   4, false, false, true),
('Sunil Narine',         'Narine',    'ALL_ROUNDER',   'LEFT_HAND_BAT',  'RIGHT_ARM_OFFBREAK',   4, false, false, true),
('Cameron Green',        'KKR-Green',   'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_MEDIUM',     4, false, false, true),
('Rachin Ravindra',      'Rachin',    'ALL_ROUNDER',   'LEFT_HAND_BAT',  'LEFT_ARM_SPIN',        4, false, false, true),
('Ramandeep Singh',      'Ramandeep', 'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_MEDIUM',     4, false, false, true),
('Anukul Roy',           'A Roy',     'ALL_ROUNDER',   'LEFT_HAND_BAT',  'LEFT_ARM_SPIN',        4, false, false, true),
('Sarthak Ranjan',       'Sarthak',   'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_MEDIUM',     4, false, false, true),
('Daksh Kamra',          'D Kamra',   'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_OFFBREAK',   4, false, false, true),
('Varun Chakaravarthy',  'Varun',     'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_LEGBREAK',   4, false, false, true),
('Matheesha Pathirana',  'Pathirana', 'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       4, false, false, true),
('Blessing Muzarabani',  'Muzarabani','BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       4, false, false, true),
('Vaibhav Arora',        'V Arora',   'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       4, false, false, true),
('Navdeep Saini',        'Saini',     'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       4, false, false, true),
('Umran Malik',          'Umran',     'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       4, false, false, true),
('Kartik Tyagi',         'K Tyagi',   'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       4, false, false, true),
('Prashant Solanki',     'Solanki',   'BOWLER',        'LEFT_HAND_BAT',  'LEFT_ARM_SPIN',        4, false, false, true),
('Saurabh Dubey',        'S Dubey',   'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       4, false, false, true);
INSERT INTO players (full_name, short_name, role, batting_style, bowling_style, team_id, captain, wicket_keeper, active) VALUES
('Travis Head',          'SRH-Head',      'BATTER',        'LEFT_HAND_BAT',  NULL,                   5, false, false, true),
('Ishan Kishan',         'SRH-Ishan',     'WICKET_KEEPER', 'LEFT_HAND_BAT',  NULL,                   5, false, true,  true),
('Heinrich Klaasen',     'Klaasen',   'WICKET_KEEPER', 'RIGHT_HAND_BAT', NULL,                   5, false, true,  true),
('Aniket Verma',         'A Verma',   'BATTER',        'RIGHT_HAND_BAT', NULL,                   5, false, false, true),
('Smaran Ravichandran',  'Smaran',    'BATTER',        'RIGHT_HAND_BAT', NULL,                   5, false, false, true),
('Salil Arora',          'S Arora',   'BATTER',        'RIGHT_HAND_BAT', NULL,                   5, false, false, true),
('Abhishek Sharma',      'SRH-A Sharma',  'ALL_ROUNDER',   'LEFT_HAND_BAT',  'RIGHT_ARM_OFFBREAK',   5, false, false, true),
('Nitish Kumar Reddy',   'N Reddy',   'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       5, false, false, true),
('Harshal Patel',        'Harshal',   'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       5, false, false, true),
('Kamindu Mendis',       'Kamindu',   'ALL_ROUNDER',   'LEFT_HAND_BAT',  'LEFT_ARM_SPIN',        5, false, false, true),
('Liam Livingstone',     'Livingstone','ALL_ROUNDER',  'RIGHT_HAND_BAT', 'RIGHT_ARM_LEGBREAK',   5, false, false, true),
('Brydon Carse',         'B Carse',   'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       5, false, false, true),
('David Payne',          'D Payne',   'ALL_ROUNDER',   'LEFT_HAND_BAT',  'LEFT_ARM_FAST',        5, false, false, true),
('Harsh Dubey',          'H Dubey',   'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_OFFBREAK',   5, false, false, true),
('Shivang Kumar',        'Shivang',   'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_MEDIUM',     5, false, false, true),
('Krains Fuletra',       'Fuletra',   'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_MEDIUM',     5, false, false, true),
('Pat Cummins',          'SRH-Cummins',   'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       5, true,  false, true),
('Shivam Mavi',          'S Mavi',    'BOWLER',        'LEFT_HAND_BAT',  'RIGHT_ARM_FAST',       5, false, false, true),
('Jaydev Unadkat',       'Unadkat',   'BOWLER',        'LEFT_HAND_BAT',  'LEFT_ARM_FAST',        5, false, false, true),
('Zeeshan Ansari',       'Ansari',    'BOWLER',        'LEFT_HAND_BAT',  'LEFT_ARM_SPIN',        5, false, false, true),
('Eshan Malinga',        'E Malinga', 'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       5, false, false, true),
('Sakib Hussain',        'Sakib',     'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       5, false, false, true),
('Onkar Tarmale',        'Tarmale',   'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_MEDIUM',     5, false, false, true),
('Amit Kumar',           'Amit',      'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       5, false, false, true),
('Praful Hinge',         'Hinge',     'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_MEDIUM',     5, false, false, true);
INSERT INTO players (full_name, short_name, role, batting_style, bowling_style, team_id, captain, wicket_keeper, active) VALUES
('Yashasvi Jaiswal',     'RR-Jaiswal',   'BATTER',        'LEFT_HAND_BAT',  NULL,                   6, false, false, true),
('Vaibhav Suryavanshi',  'Suryavanshi','BATTER',       'RIGHT_HAND_BAT', NULL,                   6, false, false, true),
('Shimron Hetmyer',      'Hetmyer',   'BATTER',        'LEFT_HAND_BAT',  NULL,                   6, false, false, true),
('Dhruv Jurel',          'D Jurel',   'WICKET_KEEPER', 'RIGHT_HAND_BAT', NULL,                   6, false, true,  true),
('Donovan Ferreira',     'Ferreira',  'BATTER',        'RIGHT_HAND_BAT', NULL,                   6, false, false, true),
('Shubham Dubey',        'Sh Dubey',  'BATTER',        'RIGHT_HAND_BAT', NULL,                   6, false, false, true),
('Lhuan-Dre Pretorius',  'Pretorius', 'BATTER',        'RIGHT_HAND_BAT', NULL,                   6, false, false, true),
('Ravi Singh',           'R Singh',   'BATTER',        'RIGHT_HAND_BAT', NULL,                   6, false, false, true),
('Aman Rao Perala',      'A Perala',  'BATTER',        'RIGHT_HAND_BAT', NULL,                   6, false, false, true),
('Riyan Parag',          'R Parag',   'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_OFFBREAK',   6, true,  false, true),
('Ravindra Jadeja',      'RR-Jadeja',    'ALL_ROUNDER',   'LEFT_HAND_BAT',  'LEFT_ARM_SPIN',        6, false, false, true),
('Yudhvir Singh Charak', 'Yudhvir',   'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       6, false, false, true),
('Dasun Shanaka',        'Shanaka',   'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_MEDIUM',     6, false, false, true),
('Jofra Archer',         'Archer',    'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       6, false, false, true),
('Ravi Bishnoi',         'R Bishnoi', 'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_LEGBREAK',   6, false, false, true),
('Sandeep Sharma',       'Sandeep',   'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_MEDIUM',     6, false, false, true),
('Tushar Deshpande',     'Tushar',    'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       6, false, false, true),
('Kwena Maphaka',        'Maphaka',   'BOWLER',        'RIGHT_HAND_BAT', 'LEFT_ARM_FAST',        6, false, false, true),
('Nandre Burger',        'Burger',    'BOWLER',        'LEFT_HAND_BAT',  'LEFT_ARM_FAST',        6, false, false, true),
('Adam Milne',           'Milne',     'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       6, false, false, true),
('Kuldeep Sen',          'K Sen',     'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       6, false, false, true),
('Sushant Mishra',       'S Mishra',  'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       6, false, false, true),
('Brijesh Sharma',       'Brijesh',   'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_MEDIUM',     6, false, false, true),
('Yash Raj Punja',       'Y Punja',   'BOWLER',        'LEFT_HAND_BAT',  'LEFT_ARM_FAST',        6, false, false, true),
('Vignesh Puthur',       'V Puthur',  'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_MEDIUM',     6, false, false, true);
INSERT INTO players (full_name, short_name, role, batting_style, bowling_style, team_id, captain, wicket_keeper, active) VALUES
('KL Rahul',             'KL Rahul',  'WICKET_KEEPER', 'RIGHT_HAND_BAT', NULL,                   7, true,  true,  true),
('Karun Nair',           'K Nair',    'BATTER',        'RIGHT_HAND_BAT', NULL,                   7, false, false, true),
('David Miller',         'Miller',    'BATTER',        'LEFT_HAND_BAT',  NULL,                   7, false, false, true),
('Pathum Nissanka',      'Nissanka',  'BATTER',        'RIGHT_HAND_BAT', NULL,                   7, false, false, true),
('Sahil Parakh',         'S Parakh',  'BATTER',        'LEFT_HAND_BAT',  NULL,                   7, false, false, true),
('Prithvi Shaw',         'P Shaw',    'BATTER',        'RIGHT_HAND_BAT', NULL,                   7, false, false, true),
('Abishek Porel',        'A Porel',   'WICKET_KEEPER', 'LEFT_HAND_BAT',  NULL,                   7, false, true,  true),
('Tristan Stubbs',       'Stubbs',    'WICKET_KEEPER', 'RIGHT_HAND_BAT', NULL,                   7, false, true,  true),
('Axar Patel',           'DC-Axar',      'ALL_ROUNDER',   'LEFT_HAND_BAT',  'LEFT_ARM_SPIN',        7, false, false, true),
('Nitish Rana',          'N Rana',    'ALL_ROUNDER',   'LEFT_HAND_BAT',  'RIGHT_ARM_OFFBREAK',   7, false, false, true),
('Sameer Rizvi',         'S Rizvi',   'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_OFFBREAK',   7, false, false, true),
('Ashutosh Sharma',      'DC-A Sharma',  'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_MEDIUM',     7, false, false, true),
('Vipraj Nigam',         'V Nigam',   'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_LEGBREAK',   7, false, false, true),
('Ajay Mandal',          'A Mandal',  'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_OFFBREAK',   7, false, false, true),
('Tripurana Vijay',      'T Vijay',   'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_MEDIUM',     7, false, false, true),
('Madhav Tiwari',        'M Tiwari',  'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_MEDIUM',     7, false, false, true),
('Mitchell Starc',       'DC-Starc',     'BOWLER',        'LEFT_HAND_BAT',  'LEFT_ARM_FAST',        7, false, false, true),
('Kuldeep Yadav',        'DC-Kuldeep',   'BOWLER',        'LEFT_HAND_BAT',  'LEFT_ARM_SPIN',        7, false, false, true),
('T. Natarajan',         'Natarajan', 'BOWLER',        'RIGHT_HAND_BAT', 'LEFT_ARM_FAST',        7, false, false, true),
('Mukesh Kumar',         'M Kumar',   'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       7, false, false, true),
('Dushmantha Chameera',  'Chameera',  'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       7, false, false, true),
('Auqib Nabi',           'A Nabi',    'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       7, false, false, true),
('Lungisani Ngidi',      'Ngidi',     'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       7, false, false, true),
('Kyle Jamieson',        'Jamieson',  'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       7, false, false, true);
INSERT INTO players (full_name, short_name, role, batting_style, bowling_style, team_id, captain, wicket_keeper, active) VALUES
('Shreyas Iyer',         'S Iyer',    'BATTER',        'RIGHT_HAND_BAT', NULL,                   8, true,  false, true),
('Prabhsimran Singh',    'Prabh',     'WICKET_KEEPER', 'RIGHT_HAND_BAT', NULL,                   8, false, true,  true),
('Shashank Singh',       'Sh Singh',  'BATTER',        'RIGHT_HAND_BAT', NULL,                   8, false, false, true),
('Nehal Wadhera',        'Wadhera',   'BATTER',        'LEFT_HAND_BAT',  NULL,                   8, false, false, true),
('Vishnu Vinod',         'V Vinod',   'WICKET_KEEPER', 'RIGHT_HAND_BAT', NULL,                   8, false, true,  true),
('Harnoor Pannu',        'H Pannu',   'BATTER',        'LEFT_HAND_BAT',  NULL,                   8, false, false, true),
('Pyla Avinash',         'Avinash',   'BATTER',        'RIGHT_HAND_BAT', NULL,                   8, false, false, true),
('Marcus Stoinis',       'PBKS-Stoinis',   'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_MEDIUM',     8, false, false, true),
('Priyansh Arya',        'P Arya',    'ALL_ROUNDER',   'LEFT_HAND_BAT',  'RIGHT_ARM_OFFBREAK',   8, false, false, true),
('Musheer Khan',         'Musheer',   'ALL_ROUNDER',   'LEFT_HAND_BAT',  'LEFT_ARM_SPIN',        8, false, false, true),
('Marco Jansen',         'Jansen',    'ALL_ROUNDER',   'LEFT_HAND_BAT',  'LEFT_ARM_FAST',        8, false, false, true),
('Azmatullah Omarzai',   'Omarzai',   'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_MEDIUM',     8, false, false, true),
('Harpreet Brar',        'H Brar',    'ALL_ROUNDER',   'LEFT_HAND_BAT',  'LEFT_ARM_SPIN',        8, false, false, true),
('Suryansh Shedge',      'Shedge',    'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_MEDIUM',     8, false, false, true),
('Mitch Owen',           'M Owen',    'ALL_ROUNDER',   'LEFT_HAND_BAT',  'RIGHT_ARM_MEDIUM',     8, false, false, true),
('Cooper Connolly',      'Connolly',  'ALL_ROUNDER',   'LEFT_HAND_BAT',  'RIGHT_ARM_OFFBREAK',   8, false, false, true),
('Ben Dwarshuis',        'Dwarshuis', 'ALL_ROUNDER',   'LEFT_HAND_BAT',  'LEFT_ARM_FAST',        8, false, false, true),
('Arshdeep Singh',       'PBKS-Arshdeep',  'BOWLER',        'LEFT_HAND_BAT',  'LEFT_ARM_FAST',        8, false, false, true),
('Yuzvendra Chahal',     'Chahal',    'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_LEGBREAK',   8, false, false, true),
('Lockie Ferguson',      'Ferguson',  'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       8, false, false, true),
('Vyshak Vijaykumar',    'Vyshak',    'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       8, false, false, true),
('Yash Thakur',          'Y Thakur',  'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       8, false, false, true),
('Xavier Bartlett',      'Bartlett',  'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       8, false, false, true),
('Pravin Dubey',         'P Dubey',   'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_LEGBREAK',   8, false, false, true),
('Vishal Nishad',        'V Nishad',  'BOWLER',        'RIGHT_HAND_BAT', 'LEFT_ARM_FAST',        8, false, false, true);
INSERT INTO players (full_name, short_name, role, batting_style, bowling_style, team_id, captain, wicket_keeper, active) VALUES
('Shubman Gill',         'GT-Gill',      'BATTER',        'RIGHT_HAND_BAT', NULL,                   9, true,  false, true),
('Jos Buttler',          'Buttler',   'WICKET_KEEPER', 'RIGHT_HAND_BAT', NULL,                   9, false, true,  true),
('Sai Sudharsan',        'Sudharsan', 'BATTER',        'LEFT_HAND_BAT',  NULL,                   9, false, false, true),
('Kumar Kushagra',       'Kushagra',  'WICKET_KEEPER', 'RIGHT_HAND_BAT', NULL,                   9, false, true,  true),
('Anuj Rawat',           'A Rawat',   'WICKET_KEEPER', 'LEFT_HAND_BAT',  NULL,                   9, false, true,  true),
('Tom Banton',           'Banton',    'WICKET_KEEPER', 'RIGHT_HAND_BAT', NULL,                   9, false, true,  true),
('Glenn Phillips',       'G Phillips','BATTER',        'RIGHT_HAND_BAT', NULL,                   9, false, false, true),
('Shahrukh Khan',        'Shahrukh',  'BATTER',        'RIGHT_HAND_BAT', NULL,                   9, false, false, true),
('Washington Sundar',    'GT-Sundar',    'ALL_ROUNDER',   'LEFT_HAND_BAT',  'RIGHT_ARM_OFFBREAK',   9, false, false, true),
('Rahul Tewatia',        'Tewatia',   'ALL_ROUNDER',   'LEFT_HAND_BAT',  'RIGHT_ARM_LEGBREAK',   9, false, false, true),
('Jason Holder',         'Holder',    'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       9, false, false, true),
('Nishant Sindhu',       'N Sindhu',  'ALL_ROUNDER',   'LEFT_HAND_BAT',  'LEFT_ARM_SPIN',        9, false, false, true),
('Jayant Yadav',         'J Yadav',   'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_OFFBREAK',   9, false, false, true),
('Sai Kishore',          'Sai Kishore','ALL_ROUNDER',  'LEFT_HAND_BAT',  'LEFT_ARM_SPIN',        9, false, false, true),
('Mohd. Arshad Khan',    'Arshad',    'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       9, false, false, true),
('Rashid Khan',          'Rashid',    'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_LEGBREAK',   9, false, false, true),
('Kagiso Rabada',        'Rabada',    'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       9, false, false, true),
('Mohammed Siraj',       'GT-Siraj',     'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       9, false, false, true),
('Prasidh Krishna',      'GT-Prasidh',   'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       9, false, false, true),
('Ishant Sharma',        'Ishant',    'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       9, false, false, true),
('Manav Suthar',         'Suthar',    'BOWLER',        'LEFT_HAND_BAT',  'LEFT_ARM_SPIN',        9, false, false, true),
('Gurnoor Singh Brar',   'Gurnoor',   'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       9, false, false, true),
('Luke Wood',            'L Wood',    'BOWLER',        'LEFT_HAND_BAT',  'LEFT_ARM_FAST',        9, false, false, true),
('Kulwant Khejroliya',   'Kulwant',   'BOWLER',        'RIGHT_HAND_BAT', 'LEFT_ARM_FAST',        9, false, false, true),
('Ashok Sharma',         'Ash Sharma','BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_MEDIUM',     9, false, false, true);
INSERT INTO players (full_name, short_name, role, batting_style, bowling_style, team_id, captain, wicket_keeper, active) VALUES
('Rishabh Pant',         'Pant',      'WICKET_KEEPER', 'LEFT_HAND_BAT',  NULL,                   10, true,  true,  true),
('Nicholas Pooran',      'Pooran',    'WICKET_KEEPER', 'LEFT_HAND_BAT',  NULL,                   10, false, true,  true),
('Josh Inglis',          'LSG-Inglis',    'WICKET_KEEPER', 'RIGHT_HAND_BAT', NULL,                   10, false, true,  true),
('Aiden Markram',        'Markram',   'BATTER',        'RIGHT_HAND_BAT', NULL,                   10, false, false, true),
('Matthew Breetzke',     'Breetzke',  'BATTER',        'RIGHT_HAND_BAT', NULL,                   10, false, false, true),
('Himmat Singh',         'Himmat',    'BATTER',        'RIGHT_HAND_BAT', NULL,                   10, false, false, true),
('Mukul Choudhary',      'Mu Choudhary','BATTER',      'RIGHT_HAND_BAT', NULL,                   10, false, false, true),
('Akshat Raghuwanshi',   'Akshat',    'BATTER',        'RIGHT_HAND_BAT', NULL,                   10, false, false, true),
('Mitchell Marsh',       'M Marsh',   'ALL_ROUNDER',   'LEFT_HAND_BAT',  'RIGHT_ARM_FAST',       10, false, false, true),
('Wanindu Hasaranga',    'Hasaranga', 'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_LEGBREAK',   10, false, false, true),
('Abdul Samad',          'Samad',     'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_MEDIUM',     10, false, false, true),
('Shahbaz Ahamad',       'Shahbaz',   'ALL_ROUNDER',   'LEFT_HAND_BAT',  'LEFT_ARM_SPIN',        10, false, false, true),
('Arshin Kulkarni',      'Arshin',    'ALL_ROUNDER',   'LEFT_HAND_BAT',  'LEFT_ARM_SPIN',        10, false, false, true),
('Ayush Badoni',         'A Badoni',  'ALL_ROUNDER',   'RIGHT_HAND_BAT', 'RIGHT_ARM_LEGBREAK',   10, false, false, true),
('Mohammad Shami',       'LSG-Shami',     'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       10, false, false, true),
('Mayank Yadav',         'LSG-M Yadav',   'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       10, false, false, true),
('Anrich Nortje',        'Nortje',    'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       10, false, false, true),
('Avesh Khan',           'LSG-Avesh',     'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       10, false, false, true),
('Mohsin Khan',          'Mohsin',    'BOWLER',        'LEFT_HAND_BAT',  'LEFT_ARM_FAST',        10, false, false, true),
('M. Siddharth',         'Siddharth', 'BOWLER',        'RIGHT_HAND_BAT', 'LEFT_ARM_SPIN',        10, false, false, true),
('Digvesh Singh',        'Digvesh',   'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       10, false, false, true),
('Akash Singh',          'Ak Singh',  'BOWLER',        'LEFT_HAND_BAT',  'LEFT_ARM_FAST',        10, false, false, true),
('Arjun Tendulkar',      'Arjun',     'BOWLER',        'LEFT_HAND_BAT',  'LEFT_ARM_FAST',        10, false, false, true),
('Naman Tiwari',         'N Tiwari',  'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       10, false, false, true),
('Prince Yadav',         'P Yadav',   'BOWLER',        'RIGHT_HAND_BAT', 'RIGHT_ARM_FAST',       10, false, false, true);

INSERT INTO tournament (
    id,
    name,
    location,
    type,
    overs,
    max_teams,
    start_date,
    end_date,
    status,
    created_by_user_id,
    logo_url,
    is_public,
    created_at,
    updated_at
) VALUES (
             1,
             'IPL 2026',
             'India',
             'LEAGUE',
             20,
             10,
             '2026-03-20',
             '2026-05-30',
             'UPCOMING',
             1,
             'https://example.com/ipl-logo.png',
             true,
             CURRENT_TIMESTAMP,
             CURRENT_TIMESTAMP
         );

INSERT INTO batter_stats (
    tournament_id,
    player_id,
    matches,
    innings,
    not_outs,
    runs,
    balls,
    fours,
    sixes,
    fifties,
    hundreds,
    ducks,
    highest_score,
    strike_rate,
    average
) VALUES (
             1,
             52,
             10,
             10,
             2,
             450,
             320,
             45,
             18,
             4,
             1,
             0,
             120,
             140.63,
             56.25
         );

INSERT INTO tournament_team(tournament_id, team_id)
VALUES
    (1, 1),
    (1, 2),
    (1, 3),
    (1, 4),
    (1, 5),
    (1, 6),
    (1, 7),
    (1, 8),
    (1, 9),
    (1, 10);